# 04a. Embeddings e indexacion base en PostgreSQL + pgvector

Este notebook implementa la carga del corpus RAG en PostgreSQL, la generacion de embeddings y la validacion de persistencia en `pgvector` usando la capa productiva de `src.vector_store`.

> Si cambias `EMBEDDING_MODEL`, reejecuta el notebook completo para regenerar los embeddings persistidos en PostgreSQL.

## Objetivos

- cargar el dataset `rag.parquet`
- crear o validar el esquema `pgvector`
- insertar convocatorias por lotes usando `src.vector_store`
- comprobar el numero de registros persistidos
- validar cobertura minima del indice vectorial y consistencia de metadatos

In [8]:
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
from IPython.display import display
from sqlalchemy import text
from tqdm import tqdm

from src.config import (
    CURATED_ENRICHED_PARQUET_PATH,
    PRIMARY_RAG_PATH,
    RAG_ENRICHED_TEXT_COLUMN,
    RAG_TEXT_COLUMN,
    settings,
)
from src.data_loader import build_retrieval_corpus
from src.vector_store import connect_db, create_schema_if_needed, insert_convocatorias

BATCH_SIZE = 64
CORPUS_MODE = "base"
SAMPLE_LIMIT: int | None = None

if CORPUS_MODE == "base":
    CORPUS_PATH = PRIMARY_RAG_PATH
    SOURCE_TEXT_COLUMN = RAG_TEXT_COLUMN
    CORPUS_VARIANT = "base"
else:
    CORPUS_PATH = CURATED_ENRICHED_PARQUET_PATH
    SOURCE_TEXT_COLUMN = RAG_ENRICHED_TEXT_COLUMN
    CORPUS_VARIANT = "enriched"

print("ROOT:", ROOT)
print("DATABASE_URL:", settings.database_url)
print("EMBEDDING_MODEL:", settings.embedding_model)
print("CORPUS_MODE:", CORPUS_MODE)
print("CORPUS_VARIANT:", CORPUS_VARIANT)
print("CORPUS_PATH:", CORPUS_PATH)
print("SOURCE_TEXT_COLUMN:", SOURCE_TEXT_COLUMN)

ROOT: /var/www/codigo/maestria_ia/umsa/diplomados_intermedios/dip_03
DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5433/sicoes_rag
EMBEDDING_MODEL: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
CORPUS_MODE: base
CORPUS_VARIANT: base
CORPUS_PATH: /var/www/codigo/maestria_ia/umsa/diplomados_intermedios/dip_03/data/rag/sicoes_convocatorias_rag.parquet
SOURCE_TEXT_COLUMN: texto_rag

## 1. Cargar corpus RAG

El corpus indexado parte del dataset RAG canónico versionado en `parquet`.

In [9]:
df = build_retrieval_corpus(
    CORPUS_PATH,
    text_column=SOURCE_TEXT_COLUMN,
    corpus_variant=CORPUS_VARIANT,
)
if SAMPLE_LIMIT is not None:
    df = df.head(SAMPLE_LIMIT).copy()

print("Filas cargadas:", len(df))
print("Columnas:", df.columns.tolist())
df[["document_id", "cuce", "entidad", "corpus_variant", RAG_TEXT_COLUMN]].head(3)

Filas cargadas: 1418
Columnas: ['document_id', 'cuce', 'entidad', 'tipo_contratacion', 'modalidad', 'objeto_contratacion', 'subasta', 'fecha_publicacion', 'fecha_presentacion', 'fecha_publicacion_iso', 'fecha_presentacion_iso', 'estado', 'archivos_disponibles', 'ficha_url', 'source_draw', 'source_row_in_page', 'longitud_objeto', 'cantidad_palabras_objeto', 'texto_rag', 'corpus_variant', 'source_text_column']

,document_id,cuce,entidad,corpus_variant,texto_rag
0,26-1803-00-1669918-1-1,26-1803-00-1669918-1-1,Gobierno Autonomo Municipal De Riberalta,base,CUCE: 26-1803-00-1669918-1-1\nEntidad: Gobiern...
1,26-1101-00-1668944-1-1,26-1101-00-1668944-1-1,Gobierno Autonomo Municipal De Sucre,base,CUCE: 26-1101-00-1668944-1-1\nEntidad: Gobiern...
2,26-1119-00-1669680-1-1,26-1119-00-1669680-1-1,Gobierno Autonomo Municipal De Camargo,base,CUCE: 26-1119-00-1669680-1-1\nEntidad: Gobiern...

## 2. Crear esquema y validar conexion

Esta celda usa el SQL de inicializacion y la configuracion de `src.vector_store`. Si falla en tu entorno, revisa `DATABASE_URL` y el estado del contenedor Docker.

In [10]:
create_schema_if_needed()
engine = connect_db()

with engine.connect() as connection:
    print("SELECT 1 ->", connection.exec_driver_sql("SELECT 1").scalar())
    table_exists = connection.exec_driver_sql(
        "SELECT to_regclass('public.convocatorias')"
    ).scalar()
    print("Tabla convocatorias:", table_exists)

SELECT 1 -> 1
Tabla convocatorias: convocatorias

## 3. Insercion por lotes

La insercion se hace mediante `insert_convocatorias()` con `upsert`, por lo que el notebook puede reejecutarse sin duplicar registros por `document_id`.

In [11]:
records = df.to_dict(orient="records")
total_batches = (len(records) + BATCH_SIZE - 1) // BATCH_SIZE
inserted_total = 0

for batch_index in tqdm(range(total_batches), total=total_batches, desc="Insertando lotes", unit="lote"):
    start = batch_index * BATCH_SIZE
    end = start + BATCH_SIZE
    batch = records[start:end]
    inserted = insert_convocatorias(batch, generate_missing_embeddings=True, upsert=True)
    inserted_total += inserted

print("Total de registros procesados:", inserted_total)
print("Total de lotes:", total_batches)

Insertando lotes: 100%|██████████| 23/23 [00:57<00:00,  2.48s/lote]

Total de registros procesados: 1418
Total de lotes: 23

## 4. Validaciones posteriores a la insercion

In [12]:
with engine.connect() as connection:
    total_rows = connection.execute(
        text("SELECT COUNT(*) FROM convocatorias WHERE corpus_variant = :corpus_variant"),
        {"corpus_variant": CORPUS_VARIANT},
    ).scalar_one()
    rows_with_embeddings = connection.execute(
        text(
            "SELECT COUNT(*) FROM convocatorias WHERE embedding IS NOT NULL AND corpus_variant = :corpus_variant"
        ),
        {"corpus_variant": CORPUS_VARIANT},
    ).scalar_one()
    sample_rows = pd.read_sql(
        text(
            """
            SELECT document_id, cuce, entidad, modalidad, estado, corpus_variant
            FROM convocatorias
            WHERE corpus_variant = :corpus_variant
            ORDER BY id
            LIMIT 5
            """
        ),
        connection,
        params={"corpus_variant": CORPUS_VARIANT},
    )

print("Filas totales en PostgreSQL:", total_rows)
print("Filas con embedding:", rows_with_embeddings)
sample_rows

Filas totales en PostgreSQL: 1418
Filas con embedding: 1418

,document_id,cuce,entidad,modalidad,estado,corpus_variant
0,26-1803-00-1669918-1-1,26-1803-00-1669918-1-1,Gobierno Autonomo Municipal De Riberalta,CNC,Vigente,base
1,26-1101-00-1668944-1-1,26-1101-00-1668944-1-1,Gobierno Autonomo Municipal De Sucre,CM,Vigente,base
2,26-1119-00-1669680-1-1,26-1119-00-1669680-1-1,Gobierno Autonomo Municipal De Camargo,ANPP,Vigente,base
3,26-1101-00-1669911-1-1,26-1101-00-1669911-1-1,Gobierno Autonomo Municipal De Sucre,CM,Vigente,base
4,26-0020-21-1664086-2-1,26-0020-21-1664086-2-1,Armada Boliviana,ANPP,Vigente,base

## 5. Validacion estructural posterior a la indexacion

Esta seccion evita mezclar ingestion con evaluacion de retrieval. Aqui solo se verifican cobertura de embeddings, unicidad y una distribucion basica de metadatos persistidos.

In [13]:
with engine.connect() as connection:
    validation_summary = pd.read_sql(
        text(
            """
            SELECT
                COUNT(*) AS total_rows,
                COUNT(DISTINCT document_id) AS unique_document_ids,
                COUNT(*) FILTER (WHERE embedding IS NOT NULL) AS rows_with_embedding,
                COUNT(*) FILTER (WHERE metadata_json IS NOT NULL) AS rows_with_metadata,
                ROUND(AVG(LENGTH(texto_rag))::numeric, 2) AS avg_texto_rag_len
            FROM convocatorias
            WHERE corpus_variant = :corpus_variant
            """
        ),
        connection,
        params={"corpus_variant": CORPUS_VARIANT},
    )
    modalidad_distribution = pd.read_sql(
        text(
            """
            SELECT modalidad, COUNT(*) AS total
            FROM convocatorias
            WHERE corpus_variant = :corpus_variant
            GROUP BY modalidad
            ORDER BY total DESC, modalidad ASC
            LIMIT 10
            """
        ),
        connection,
        params={"corpus_variant": CORPUS_VARIANT},
    )

display(validation_summary)
display(modalidad_distribution)

,total_rows,unique_document_ids,rows_with_embedding,rows_with_metadata,avg_texto_rag_len
0,1418,1418,1418,1418,422.3

  modalidad  total
0      ANPP    447
1      ANPE    414
2        CM    188
3       CNC    121
4        LP     97
5      CND1     75
6        OF     75
7        CD      1

## 6. Chequeos rapidos de consistencia

In [14]:
with engine.connect() as connection:
    consistency_checks = pd.read_sql(
        text(
            """
            SELECT
                COUNT(*) FILTER (WHERE cuce IS NULL OR cuce = '') AS missing_cuce,
                COUNT(*) FILTER (WHERE entidad IS NULL OR entidad = '') AS missing_entidad,
                COUNT(*) FILTER (WHERE objeto_contratacion IS NULL OR objeto_contratacion = '') AS missing_objeto,
                COUNT(*) FILTER (WHERE texto_rag IS NULL OR texto_rag = '') AS missing_texto_rag,
                COUNT(*) - COUNT(DISTINCT cuce) AS duplicate_cuce_gap
            FROM convocatorias
            WHERE corpus_variant = :corpus_variant
            """
        ),
        connection,
        params={"corpus_variant": CORPUS_VARIANT},
    )
    estado_distribution = pd.read_sql(
        text(
            """
            SELECT estado, COUNT(*) AS total
            FROM convocatorias
            WHERE corpus_variant = :corpus_variant
            GROUP BY estado
            ORDER BY total DESC, estado ASC
            """
        ),
        connection,
        params={"corpus_variant": CORPUS_VARIANT},
    )

display(consistency_checks)
display(estado_distribution)

,missing_cuce,missing_entidad,missing_objeto,missing_texto_rag,duplicate_cuce_gap
0,0,0,0,0,0

    estado  total
0  Vigente   1418

## 7. Observaciones

- Este notebook reutiliza la capa `src.vector_store` para evitar duplicacion de logica.
- La evaluacion comparativa de retrieval (`keyword`, `semantic`, `hybrid`) se realiza en `05_rag_evaluation.ipynb`.
- Si la conexion local falla, verificar Docker, `DATABASE_URL` y que el puerto configurado en `.env` este accesible desde el entorno Python usado por el notebook.